### PR TITLE
Improving mobile performance issues for blog website

### PR DESCRIPTION
**Pull request by sahadat-sk**
fixes issue: [#1592](https://github.com/keploy/keploy/issues/1592)

Light house score

image

### CODE REVIEW

**Comment by sahadat-sk** [comment]
Hey @nehagup , can you please review the canges

**Comment by anmolchhabra21** [comment]
Hi @sahadat-sk, I went through your changes, can you please let me know what was the blocker that was decreasing the performance, as I found only one package named sharp imported, and some linting changes, I couldn't find how the issue was resolved, can you please let me know?

**Comment by sahadat-sk** [comment]
Hey @anmolchhabra21, the significant update here is in the hero section. Instead of the usual img tag, we've implemented the Image component from next/image. This change automatically optimizes the images. Hope this helps!

**Review by nehagup — CHANGES_REQUESTED** [review]
@sahadat-sk thanks for the initiative! Just by looking at the report, I can see that desktop and mobile performance has declined significantly while accessibility has improved! 

Screenshot 2024-02-28 at 1 54 48 PM

https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fkeploy.io%2Fblog&strategy=desktop&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext 

Screenshot 2024-02-28 at 1 51 02 PM

Screenshot 2024-02-28 at 1 50 36 PM

**Comment by nehagup** [comment]
> Hi @nehagup, just to make sure, are you using the production setup (running "npm run build" followed by "npm run start") for the site? Development mode ("npm run dev") isn't as optimized for performance.

Hi @sahadat-sk the build is failing.

**Comment by sahadat-sk** [comment]
@nehagup can you check now?

**Review by nehagup — COMMENTED** [review]
@sahadat-sk the build is still failing. 

```
> build
> next build


Failed to compile.

./pages/authors/[slug].tsx
20:18  Error: React Hook "useRouter" is called in function "authorPage" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use".  react-hooks/rules-of-hooks

./pages/index.tsx
32:23  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
67:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/AuthorMapping.tsx
65:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/alert.tsx
18:15  Error: Do not use an `<a>` element to navigate to `/api/exit-preview/`. Use `<Link />` from `next/link` instead. See: https://nextjs.org/docs/messages/no-html-link-for-pages  @next/next/no-html-link-for-pages

./components/header.tsx
119:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/layout.tsx
15:7  Warning: Prefer `next/script` component when using the inline script for Google Analytics. See: https://nextjs.org/docs/messages/next-script-for-ga  @next/next/next-script-for-ga

./components/postByAuthorMapping.tsx
22:17  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/tweets.tsx
14:13  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
   Linting and checking validity of types  .%
```

**Comment by nehagup** [comment]
My bad! those build errors were because of the latest node version. I fixed those errors in the latest main, however after resolving conflicts with this branch there are build errors. 

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
   ▲ Next.js 14.0.1
   - Environments: .env.local

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Collecting page data
   Generating static pages (5/204)  [   =]
TypeError: Cannot read properties of undefined (reading 'includes')
    at formatAuthorName (/Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:2728)
    at /Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:724
    at Array.forEach (<anonymous>)
    at AuthorMapping (/Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:706)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)

Error occurred prerendering page "/authors". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'includes')
    at formatAuthorName (/Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:2728)
    at /Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:724
    at Array.forEach (<anonymous>)
    at AuthorMapping (/Users/neha/open-source/blog-website/.next/server/pages/authors.js:1:706)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
 ✓ Generating static pages (204/204)

> Export encountered errors on following paths:
	/authors
```

**Comment by nehagup** [comment]
Hi @sahadat-sk closing this one since this PR has been stale. Please feel free to re-open this once you're ready.

**Pull request closed without merging**
