### PR TITLE
implement content table for blog post #1240

### PR DESCRIPTION
**Pull request by hubsMIT1**
### Description
- feat: [#1240](https://github.com/keploy/keploy/issues/1240)
### Screenshot
[Demo Link](https://www.loom.com/share/2781f866c05e43e2a7432878cc6374be)

### CODE REVIEW

**Comment by aniketbamotra** [comment]
@hubsMIT1 I can't access the demo link and I don't see any changes in the website as well.

**Comment by hubsMIT1** [comment]
> @hubsMIT1 I can't access the demo link and I don't see any changes in the website as well.

can you check now link is working

**Comment by hubsMIT1** [comment]
> @hubsMIT1 I can't access the demo link and I don't see any changes in the website as well.

https://github.com/hubsMIT1/blog-website/tree/implement-and-rectify-table-of-content
with comments [implement content table #1240](https://github.com/hubsMIT1/blog-website/commit/f5c64ed47541c30a2ac4fb82cbcb276e318ec1b0)

**Comment by aniketbamotra** [comment]
Try to also put the content table at the centre for the desktop view!

**Review by nehagup — CHANGES_REQUESTED** [review]
Hey @hubsMIT1 thanks for the initiative. When I run this locally it shows empty ToC on the sidebar - 
Screenshot 2024-01-31 at 2 55 44 PM


The sidebar ToC looks good, however, styling needs to change, you can refer to docs website repo or website itself and try to match styling, something like https://keploy.io/docs/server/linux/installation/ 

Please lmk if you have any questions

**Comment by Aditya-eddy** [comment]
Hey @aniketbamotra  @nehagup Is this issue being worked on or can I work on it??

**Comment by nehagup** [comment]
@Aditya-eddy feel free to pick this up! It's been a while so closing this PR.

**Pull request closed without merging**
