### PR TITLE
Creating author profile

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the [issue](https://github.com/keploy/keploy/issues/1623).

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup I've created the Author's Profile. I'll attach the relevant screenshots. WIl be waiting on the feedback!!
Screenshot from 2024-02-28 09-06-12

**Review by nehagup — CHANGES_REQUESTED** [review]
Thanks for the initiative @Aditya-eddy! A couple of changes - 

1. Please add more margin on top of "Posts by XYZ_Author"
2. The description and details of some authors are not being fetched, for example - /blog/authors/Arindam 
3. Also, please remove the emails it might become spamy for users due to crawlers spam
4. We also need to ensure that if there's no data for any of the fields for an author, we either show N/A or don't show that field. 
5. The same author card needs to be added at the bottom of the post in the author section as well.
6. We also need to correctly format the description of the author, for example - next liners, lists are not visible.   
7. This can be unrelated to this issue, but since you worked on this - the /blog/authors page is not displaying the pictures right.

**Comment by Aditya-eddy** [comment]
Hey @nehagup addressing the above points:-
1. I have added margin-top here.
2. This issue is because the ppmaAuthorName stored is different from the Guest Author Name. It needs to be fixed at the backend first!.
3. I have removed the emails.
4. I have added this feature as well.
5. This is currently an open [issue](https://github.com/keploy/keploy/issues/1594) and people are working on it. If you want I'll go and implement it!.
6. I have added lists as seprated lines Will attach the screenshots.
7. We discussed the last issue on slack.
Screenshot from 2024-03-05 10-24-30
Screenshot from 2024-03-05 09-56-25

**Review by nehagup — CHANGES_REQUESTED** [review]
Hi @Aditya-eddy ! Thanks for making the changes. I find the following issues in merging this one -

- The author card is not responsive, since the blog-website is majorly used on mobile, need to make this responsive.
Screenshot 2024-03-06 at 2 34 14 PM

- I don't think anyone has opened a PR yet to resolve the author card in individual post in [this issue](https://github.com/keploy/keploy/issues/1594), please go ahead and make the changes in this PR, since we can use the same author card component.

**Comment by Aditya-eddy** [comment]
Hey @nehagup I succesfully added the author cards. View posts is still not there because it is currently being solved in a issue and will be there when we merge it. I'll attach the screenshots.
Screenshot from 2024-03-07 09-29-07
Screenshot from 2024-03-07 09-27-25

**Review by nehagup — CHANGES_REQUESTED** [review]
Hi @Aditya-eddy ! Please try fixing the build warnings introduced - 

```
./components/author-description.jsx
54:6  Warning: React Hook useEffect has a missing dependency: 'AuthorNameNew'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
72:11  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
79:11  Warning: Using `<img>` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

```

The responsiveness looks fine, however 
- The "Show More" or "Show Less" button is still visible even if the description text is not long and expanded. 
- If the author's images are not rightly available on /blog/authors, can you please put a default avatar image for all authors? Right now there's wrong image shown.

**Comment by nehagup** [comment]
@Aditya-eddy https://github.com/keploy/blog-website/pull/21 PR is merged, please add the same redirection as "View All Posts" to the author name, picture as well.

**Comment by Aditya-eddy** [comment]
Hey @nehagup I've removed the error. Their is one showing in Image tag to add src. But I have already added src in it.
I'll attach the screenshots for the authorcards. WIll be waiting on feedback.
I've also corrected the author's Image.
Screenshot from 2024-03-07 16-41-14

**Review by nehagup — APPROVED** [review]
LGTM! Thanks @Aditya-eddy 🎉

**Pull request merged**
