### PR TITLE
[fix] Build warning on image optimization

### PR DESCRIPTION
**Pull request by sahadat-sk**
Fixes issue :  [#1770](https://github.com/keploy/keploy/issues/1770)

Changes:

- Use next/image in pages, 'component/header.tsx', 'pages/index.tsx', and 'components/tweets.tsx'
- Install the sharp package as recommended by next.js

### CODE REVIEW

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @sahadat-sk please revert back linting changes It can cause conflicts.The build is working fine now!

**Comment by sahadat-sk** [comment]
> Hey @sahadat-sk please revert back linting changes It can cause conflicts.The build is working fine now!

I have reverted the linting changes, can you please review it?

**Comment by Hermione2408** [comment]
> > Hey @sahadat-sk please revert back linting changes It can cause conflicts.The build is working fine now!
> 
> I have reverted the linting changes, can you please review it?

Hey @sahadat-sk this issue is now resolved with PR #38

**Comment by Hermione2408** [comment]
> > > Hey @sahadat-sk please revert back linting changes It can cause conflicts.The build is working fine now!
> > 
> > 
> > I have reverted the linting changes, can you please review it?
> 
> Hey @sahadat-sk this issue is now resolved with PR #38

Hey @sahadat-sk I am closing this PR as it is fixed now with PR #38

**Pull request closed without merging**
