### PR TITLE
Correct routing

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes [issue](https://github.com/keploy/keploy/issues/1733)
[Screencast from 29-03-24 11:58:37 AM IST.webm](https://github.com/keploy/blog-website/assets/70089590/5efb429c-802f-48ef-aed9-8aeb4a1d3853)

### CODE REVIEW

**Comment by Sonichigo** [comment]
That's a good idea, it's better to have a fallback to /community, /technology as it would make finding the blog much easier for the user.

**Comment by Aditya-eddy** [comment]
Yup fixed it please check @Sonichigo , @Hermione2408.

**Comment by Aditya-eddy** [comment]
Hey @Hermione2408 @Sonichigo I was thinking of developing a personalized 404 blog not found page for /comunity and /technology and then routing them to /community and /technology url how does that sound?

**Comment by Aditya-eddy** [comment]
Made this should we make it more good styling wise?
image

**Comment by Hermione2408** [comment]
> Made this should we make it more good styling wise? image Will redirect to /community , /technology page in 2 secs.

Hey @Aditya-eddy you can use this image 
emptyTc

**Comment by Aditya-eddy** [comment]
Does this look good?
Screenshot from 2024-04-03 08-51-27

**Comment by Hermione2408** [comment]
> Does this look good? Screenshot from 2024-04-03 08-51-27

This looks good, @Aditya-eddy, but there's a background color mismatch. Could you use the version without a background? It will blend more seamlessly. 
emptyTc-removebg-preview

**Comment by Aditya-eddy** [comment]
Yup  made the changes:
Screenshot from 2024-04-05 04-43-56

**Review by Hermione2408 — APPROVED** [review]
LGTM! @nehagup

**Review by nehagup — APPROVED** [review]

**Pull request merged**
