### PR TITLE
Fix overflowing video in blogs

### PR DESCRIPTION
**Pull request by suvanbanerjee**
Closes https://github.com/keploy/keploy/issues/2163

Screenshot after fix
image

### CODE REVIEW

**Comment by suvanbanerjee** [comment]
@Sonichigo please review

**Comment by Sonichigo** [comment]
@Aditya-eddy can you take a look once?

**Comment by Aditya-eddy** [comment]
Build and the pr works!! Nice Work!

**Comment by suvanbanerjee** [comment]
@Hermione2408 please review

**Review by nehagup — APPROVED** [review]

**Comment by suvanbanerjee** [comment]
image
@nehagup, there's an issue with the wp-caption class, causing the max width to exceed on mobile devices. I'm pushing a commit to address this in the PR. Please review.

**Comment by suvanbanerjee** [comment]
> Hey @suvanbanerjee can you share me which blog are you viewing?

https://keploy.io/blog/technology/revolutionising-unit-test-generation-with-llms 
check on mobile mode or on a mobile device

**Comment by Aditya-eddy** [comment]
Hey @suvanbanerjee while seeing this there is also problem with the video:
image
Screenshot from 2024-08-08 23-25-59
Can you please make pr to make the it reposnsive on smaller screens?

**Comment by suvanbanerjee** [comment]
@Aditya-eddy The video issue has been resolved in this PR. However, it seems like the changes aren't showing up on keploy.io because a build needs to be triggered on the website repo.

@nehagup I'm not sure why the updates from the PR aren't being reflected on the website after the merge.

**Pull request merged**
