### PR TITLE
Remove: unnecessary imports present in the codebase

### PR DESCRIPTION
**Pull request by its-kunal**
This pull request fixes the issue - [Link](https://github.com/keploy/keploy/issues/1767)

Removed all unused imports from the codebase.

### CODE REVIEW

**Comment by Hermione2408** [comment]
Hey @its-kunal, could you move your changes from PRs #35, #36, #37, and #38 into a single PR? It would be helpful

**Comment by its-kunal** [comment]
Hey @Hermione2408, I have merged other PRs into this PR successfully.

**Comment by Hermione2408** [comment]
> Hey @Hermione2408, I have merged other PRs into this PR successfully.

Please close all the other PRs related to this

**Comment by Hermione2408** [comment]
@its-kunal build is failing, Please build locally before pushing the changes 
Screenshot from 2024-04-03 12-31-24

**Comment by its-kunal** [comment]
@Hermione2408 build is successful now.

**Review by Hermione2408 — APPROVED** [review]
LGTM @nehagup

**Review by nehagup — APPROVED** [review]

**Pull request merged**
