### PR TITLE
in the blog page made some changes

### PR DESCRIPTION
**Pull request by arup1221**
Enhanced: The blog page design have some changes

issue: #2387   [Better template for Keploy's blog page](https://github.com/keploy/keploy/issues/2387)

Description:

This pull request updates design of the community blog page.

### CODE REVIEW

**Comment by arup1221** [comment]
Uploading Screen Recording 2024-10-29 at 6.08.00 PM.mov…

**Comment by arup1221** [comment]
https://github.com/user-attachments/assets/eb57d347-be3d-48d9-819c-e9fc4ff39bf2

**Comment by arup1221** [comment]
https://github.com/user-attachments/assets/9fbd7361-574a-4f23-8c7b-eac5e62b1d11

**Comment by arup1221** [comment]
@TvisharajiK Please check my PR and provide feedback

**Comment by TvisharajiK** [comment]
Hey the pink doesn't sit well with the color theme

**Comment by arup1221** [comment]
Screenshot 2024-10-31 at 12 16 17 AM






### @TvisharajiK,  is it looks fine?

**Comment by Hermione2408** [comment]
@TvisharajiK can you please review!

**Comment by Hermione2408** [comment]
Thank you for your effort on this @arup1221 ! However, the changes don’t align with the current requirements, and we’ll be closing this PR for now. Feel free to contribute again in the future. Great effort! ⭐

**Pull request closed without merging**
