### PR TITLE
Changed the links color to orange

### PR DESCRIPTION
**Pull request by charanbhatia**
Changed the link color on the blog page similar to the one in the docs to orange. 

closes #2198

### CODE REVIEW

**Comment by TvisharajiK** [comment]
@charanbhatia the orange needs to be from the brand colors

**Review by Aditya-eddy — CHANGES_REQUESTED** [review]
Hey @charanbhatia  thanks for the pr. Couple of changes:
1. Can you please only change the color of the links in the blog content only and not all of the a links like the buttons on the main homepage have also changed.

**Comment by TvisharajiK** [comment]
@charanbhatia Did you make the change as per @Aditya-eddy 's comment

**Comment by charanbhatia** [comment]
> @charanbhatia Did you make the change as per @Aditya-eddy 's comment

@TvisharajiK Yes, I made all the changes as per @Aditya-eddy's comment

**Comment by TvisharajiK** [comment]
I don't think it is reflecting

**Review by Aditya-eddy — CHANGES_REQUESTED** [review]
Hey @charanbhatia currently the changes are not being reflected in the blogs. Please refer the screenshot for more:
image

**Comment by nehagup** [comment]
@charanbhatia still working on this?

**Comment by nehagup** [comment]
Hi @charanbhatia closing this for being stale, please feel free to re-open this once you make progress.

**Pull request closed without merging**
