### PR TITLE
Added the Testimonial section

### PR DESCRIPTION
**Pull request by Swpn0neel**
This PR addresses [this issue](https://github.com/keploy/keploy/issues/1552)

**Here are some screenshots of the Testimonials section:**
<br>
(Desktop View)
image
<br>
(Mobile View)
image

### CODE REVIEW

**Review by nehagup — COMMENTED** [review]
Thanks for the PR @Swpn0neel ! 

couple of changes this would require. - 

- Since it's certain these are going to be tweets, how about adding twitter cards/preview. Something like 
Screenshot 2024-02-19 at 4 24 15 PM

- Since there can be lot more tweets, we can maybe introduce a carousel (I liked how hasura have done it) - this way there can be N cards and there'll be no scaling issues. 


- Please also add the hyperlink to the original tweet on the card

**Comment by Swpn0neel** [comment]
Hey @nehagup, I can implement the card preview and add the hyperlink to the original tweet, but that carousel will affect the site load-time because we have to accommodate multiple tweets, and also we are using a container component to render the site content, so the carousel will break that, and may cause issues in the responsiveness of the site...
Without using carousel, we can accommodate around 12-15 tweets without any such adverse conditions!!
Let me know your opinion!!

**Comment by nehagup** [comment]
> Hey @nehagup, I can implement the card preview and add the hyperlink to the original tweet, but that carousel will affect the site load-time because we have to accommodate multiple tweets, and also we are using a container component to render the site content, so the carousel will break that, and may cause issues in the responsiveness of the site... Without using carousel, we can accommodate around 12-15 tweets without any such adverse conditions!! Let me know your opinion!!

@Swpn0neel that sounds reasonable. Please let me know how are you planning to accommodate ~15 tweets? If there are too many cards the section would become cluttered and long.

**Comment by Swpn0neel** [comment]
Hey @nehagup, it would kind of look like this one, and shouldn't take more than 100-120vh in desktop. And it would also be great if you can provide me the tweets, I would be able to represent them better to you, in that way!! <br>

image

**Comment by nehagup** [comment]
@Swpn0neel here's a list -

- https://x.com/yamamoto_febc/status/1755802346188390531?s=20
- https://x.com/matsuu/status/1747448928575099236?s=20
- https://x.com/Seipann11/status/1755989987039064103?s=20
- https://x.com/netmarkjp/status/1754639979635245508?s=20
- https://x.com/helloyuki_/status/1753746555537182762?s=20
- https://x.com/Kind_Of_Akash/status/1754207010470736165?s=20
- https://x.com/kyongshiii06/status/1753030333128495470?s=20
- https://x.com/techeten/status/1749066739038699717?s=20
- https://x.com/ShivamSouravJha/status/1747517726749286713?s=20
- https://x.com/AndooBomber/status/1747663021747691808?s=20
- https://x.com/__alter123/status/1731985031521014236?s=20
- https://x.com/someone7140/status/1744236263090299009?s=20
- https://x.com/ymnk_8752/status/1745458928698450057?s=20
- https://x.com/mugi_uno/status/1745726154924003502?s=20
- https://x.com/kyongshiii06/status/1746532217336250821?s=20
- https://x.com/JustADude404/status/1746888711491424681?s=20
- https://x.com/jambowrd/status/1743289008082571418?s=20

**Comment by Swpn0neel** [comment]
Most of them are non-English languages, so should I translate them and put it in the site?

**Comment by nehagup** [comment]
> Most of them are non-English languages, so should I translate them and put it in the site?

@Swpn0neel yes please, you'd see the translation on x platform itself.

**Comment by Swpn0neel** [comment]
Yeah yeah, got it!!

**Comment by Swpn0neel** [comment]
Hey @nehagup, Added 12 tweets from the links you have given me, added more info about the users so that it reflects their twitter status, and also hyperlinked the original tweets on the card. <br>
(Desktop View)
image
<br>
(Mobile View)
image

**Comment by nehagup** [comment]
> Hey @nehagup, Added 12 tweets from the links you have given me, added more info about the users so that it reflects their twitter status, and also hyperlinked the original tweets on the card. 

Mojorly looks good, we just need to add a twitter /X logo on every card to show it's a tweet and maybe we can make a carousel in case of sm (mobile) screen size otherwise it'll be a too long scroll! WDYT?

**Comment by Swpn0neel** [comment]
Hey @nehagup, I've added the Twitter/X logo to the cards, and I've tried to give a carousel for the small screens, but it's making the tweets unreadable because of the small available screen width... But to avoid the long scroll, I have taken into consideration about the scale, and so it won't be a long scroll for the mobile devices!!

**Comment by Swpn0neel** [comment]
Hey @nehagup, any update?

**Review by nehagup — CHANGES_REQUESTED** [review]
This looks great @Swpn0neel ! Just need to make a bit more responsive, currently it's breaking on iPadMini screen range (attached ss). 

Also, can you please make the target blank so that the tweet opens up in new tab?

Screenshot 2024-02-28 at 1 12 50 PM

**Review by nehagup — COMMENTED** [review]
@Swpn0neel the responsiveness looks fine now, however the profile image is breaking for a tweet 

Screenshot 2024-03-03 at 11 09 41 PM


Rest things looks good, just that build errors need to be fixed.

**Comment by Swpn0neel** [comment]
@nehagup I've fixed it!! Hope you will be able to merge the PR now!!

**Review by nehagup — APPROVED** [review]

**Pull request merged**
