### PR TITLE
Types for the blog website

### PR DESCRIPTION
**Pull request by its-kunal**
This PR fixes the [issue](https://github.com/keploy/keploy/issues/1768)

- Add types to the codebase.

### CODE REVIEW

**Comment by its-kunal** [comment]
Hey @nehagup, please review the code.

**Comment by Hermione2408** [comment]
Hey @its-kunal there are lots of conflicts please resolve them

**Comment by Hermione2408** [comment]
> Hey @Hermione2408, I resolved the conflicts with the main branch.

Hey @its-kunal it still have conflict please resolve it

**Comment by its-kunal** [comment]
Hey @Hermione2408, I have resolved all the conflicts with the base branch.

**Comment by its-kunal** [comment]
Hey @Hermione2408, can you please review it.

**Review by Hermione2408 — APPROVED** [review]
LGTM @nehagup,The type definitions are clear and build is also working fine.

**Comment by Swpn0neel** [comment]
@Hermione2408 please review this PR

**Review by Hermione2408 — APPROVED** [review]
LGTM!

**Pull request merged**
