### PR TITLE
implement the footer section in the blog website #1236

### PR DESCRIPTION
**Pull request by hubsMIT1**
### Description
 - feat : implement footer [#1236](https://github.com/keploy/keploy/issues/1236)
 - Really sorry about that, accidentally deleted the .git file and things got a bit messy for me!
 
### Screenshots
image

### CODE REVIEW

**Comment by aniketbamotra** [comment]
I'm still getting the "hydration error". You need to check if all the tags are closed or not.

image

**Comment by hubsMIT1** [comment]
> I'm still getting the "hydration error". You need to check if all the tags are closed or not.
> 
> image

its working for me😥
https://www.loom.com/share/a63c705794e840279e146de1c51c4e52

**Comment by aniketbamotra** [comment]
can you check the console for any errors?

**Comment by nehagup** [comment]
Thanks for the contribution 👏 @hubsMIT1 I needed to resolve the hydration err in this PR to resolve this so made a new https://github.com/keploy/blog-website/pull/8

**Pull request closed without merging**
