### PR TITLE
[fix] Table of Contents Positioning Issue on Medium Screens

### PR DESCRIPTION
**Pull request by sahadat-sk**
Fixes: [#1771](https://github.com/keploy/keploy/issues/1771)

### CODE REVIEW

**Review by Hermione2408 — CHANGES_REQUESTED** [review]
Hey @sahadat-sk If you checkout to this size you can see that now table of content's content is overflowing we need to fix for it, can be done with dropdown on top 
To replicate you can checkout to nesthub screen size 
Screenshot from 2024-04-03 13-05-54

**Comment by sahadat-sk** [comment]
Hey @Hermione2408, I have changed the table of contents to scroll whenever it overflows, can you please review it?

**Comment by sahadat-sk** [comment]
@Hermione2408 I have made the changes, can you review them now?

**Comment by Hermione2408** [comment]
> @Hermione2408 I have made the changes, can you review them now?

Hey @sahadat-sk, I've noticed some inconsistencies across screen sizes—like the scrollbar in the TOC and varying dropdown sizes. Also, the transitions aren’t smooth; there’s a noticeable flicker. Could you take a look to ensure a more uniform experience and smoother transitions? 

Screenshot from 2024-04-05 16-05-10


[Screencast from 05-04-24 04:05:24 PM IST.webm](https://github.com/keploy/blog-website/assets/78696767/ce70f279-cd2e-4749-aa92-ece91ea6eb47)

**Review by Hermione2408 — APPROVED** [review]
LGTM @nehagup

**Review by nehagup — COMMENTED** [review]
Hi @sahadat-sk things look good, just that, there's a warning induced during build with this PR. 
Can you please check?
```


./components/TableContents.tsx
56:6  Warning: React Hook useEffect has a missing dependency: 'setIsList'. Either include it or remove the dependency array. Mutable values like 'tocRef.current' aren't valid dependencies because mutating them doesn't re-render the component.  react-hooks/exhaustive-deps
```

**Comment by sahadat-sk** [comment]
Hi @nehagup, could you please verify whether the build error persists at the moment?

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
Thanks for the contribution @sahadat-sk ! LGTM 👏

**Pull request merged**
