### PR TITLE
Enhance Home Page Design of Blog Website for Latest Posts Display

### PR DESCRIPTION
**Pull request by sahadat-sk**
Fixing issue: [#1237](https://github.com/keploy/keploy/issues/1237)

Changed the layout of blogs in "/blogs/technology" and "/blogs/community" route.

### CODE REVIEW

**Comment by sahadat-sk** [comment]
Hey @nehagup, just to be clear, should we put all the blogs under "/blog" with tech/community categories? Or should we keep "/technology" and "/community" separate, using "/blog" for top posts and linking to those routes?

**Comment by nehagup** [comment]
> Hey @nehagup, just to be clear, should we put all the blogs under "/blog" with tech/community categories? Or should we keep "/technology" and "/community" separate, using "/blog" for top posts and linking to those routes?

Hey @sahadat-sk there would be 2 CTA buttons like now one leading to tech blog and the other to community one. Below that there should be a 6 blogs preview with a given list of URL (you can choose any 6 for now, we'll timely update those URLs). Does that make sense?

**Comment by sahadat-sk** [comment]
@nehagup, I've updated the /blog page. It now has two sections, one for tech blogs and one for community blogs. Each section shows three blogs and includes a link to its page. Let me know if you think any changes are necessary. Thanks!


image

**Review by nehagup — COMMENTED** [review]
Thanks for the changes! Please revert the hero section as it is currently, rest looks good!

**Comment by sahadat-sk** [comment]
@nehagup I have reverted the hero section to the previous version, please review it.

image

**Review by nehagup — COMMENTED** [review]
@sahadat-sk can you please re-check! 

The current one is this
Screenshot 2024-02-15 at 8 22 03 PM

The screenshot you attached is pretty different.

**Comment by sahadat-sk** [comment]
@nehagup, please check now


image

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
Thanks @sahadat-sk ! 👏

**Pull request merged**
