### PR TITLE
Changes in the meta tag and the layout tag and the changes that follows

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the [issue](https://github.com/keploy/keploy/issues/1503)

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
I'll attach the video in which the metadata shows different images.
Let's summarize what I did:-
1. On the Homepage it will the show basic HOME_OG_URL which it has been showing.
2. On any page which consists technology or the community page. Upon sharing it will show the HeroPosts (The main Post which is on the top) 's image.
3. On the slug it will show the current selected post's image.
[Uploading Screencast from 06-02-24 03:51:28 PM IST.webm…]()

**Comment by Sonichigo** [comment]
@Aditya-eddy you can update `fill-rule` to `fillRule` to fix the errors showing in Console!

**Comment by Aditya-eddy** [comment]
Hey @Sonichigo thanks for the feedback!!.We surely get to it. But did I address the issue correctly?

**Review by nehagup — COMMENTED** [review]
Thanks for this PR! 👏

You're in the right direction, however it'll be great to add a twitter compatible preview as well.

also, I think the title and the description of the page should be part of the preview content. 

There's also a warning around the image size that needs to be adjusted for the preview. 

I reviewed this using https://chrome.google.com/webstore/detail/social-share-preview/ggnikicjfklimmffbkhknndafpdlabib/related?hl=en

**Comment by Aditya-eddy** [comment]
Does these ScreenShots for X preview look correct?
Screenshot from 2024-02-08 10-12-20
Screenshot from 2024-02-08 10-09-30
Screenshot from 2024-02-08 10-08-57

**Review by nehagup — APPROVED** [review]

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
@Aditya-eddy Thanks for the PR! 👏

**Comment by Aditya-eddy** [comment]
@nehagup Thanks for the feedback through the process and being patient with me!!

**Pull request merged**
