### PR TITLE
[WIP]:Add newsletter Subscription component in single post page

### PR DESCRIPTION
**Pull request by its-kunal**
Form for subscription of newsletter in single post page.
This pull request will fix issue - #1665 of keploy/keploy [Issue Link](https://github.com/keploy/keploy/issues/1665)

@nehagup can you please share more details API to call for form submission.

### CODE REVIEW

**Comment by its-kunal** [comment]
@nehagup, can you provide more details about API calls for "Subscribe to Newsletter" form.

**Review by nehagup — COMMENTED** [review]
Thanks for the initiative @its-kunal ! Can you please make the form static while the rest of the content body is being scrolled? Just like Table of content

Once we have the design finalised, you can use the same API as https://github.com/keploy/website/blob/e8119421616c10cc18af744708bbdf3acb3003d5/components/newsletter.tsx#L5

**Comment by its-kunal** [comment]
Sure @nehagup

**Comment by nehagup** [comment]
@its-kunal can you please resolve the merge conflicts?

**Comment by its-kunal** [comment]
@nehagup, resolved the merge conflicts with main branch.

**Comment by its-kunal** [comment]
OK

**Comment by Hermione2408** [comment]
Moved changes to this PR- https://github.com/keploy/blog-website/pull/30

**Comment by its-kunal** [comment]
Hey @nehagup, @Hermione2408 my commit is not visible in the new PR. I would appreciate if you include my commit in the final changes.

**Comment by Hermione2408** [comment]
Hey , i have added your commit in main PR

**Pull request closed without merging**
