### PR TITLE
Fixing:Adding More Stories.

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the [issue](https://github.com/keploy/keploy/issues/1553).
1. Added More stories and currently at default ...at 8 stories.

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup I think we can add a show more Button which displays more stories on clicking.

**Review by nehagup — COMMENTED** [review]
while this is good, it's preferrable that the tech blogs are showcased here first because those are majorly well-researched and dev oriented while the other blogs are guest posts majorly. If the number of tech blogs are lesser than 8 then we can start adding community category blogs.

**Comment by nehagup** [comment]
> Hey @nehagup I think we can add a show more Button which displays more stories on clicking.

I think that'll be a good idea.

**Comment by Aditya-eddy** [comment]
Hey @nehagup Changes made by me :-
1. Now in every post if it is  of community's category, first it will show some community posts and then some technology posts in the more stories section.
2. Now in every post if it is  of technology category, first it will show some technology posts and then some community posts in the more stories section.
3. Added a view more Button on the more Stories.

But I also added a view more button in the "/blog/community" and "blog/technology". I think It make page cleaner. But the changes can also be reverted. Will be waiting on your feedback Thanks.!!
(ScreenShots)
Screenshot from 2024-02-15 05-30-06
Screenshot from 2024-02-15 05-29-24
Screenshot from 2024-02-15 05-29-12

**Comment by nehagup** [comment]
Hey @Aditya-eddy ! Please find my comments inline. 

> 1. Now in every post if it is  of community's category, first it will show some community posts and then some technology posts in the more stories section.
Sounds good!

> 2. Now in every post if it is  of technology category, first it will show some technology posts and then some community posts in the more stories section.
Sounds good!

> 3. Added a view more Button on the more Stories.
> If the changes are all right I'll push the code.

How is this different than 1 or 2? Also, the view more button can be made a bit more cleaner and subtle. Maybe something like - 
Screenshot 2024-02-15 at 8 24 33 PM

> But I also added a view more button in the "/blog/community" and "blog/technology". I think It make page cleaner. But the changes can also be reverted. Will be waiting on your feedback Thanks.!! (ScreenShots)

I think this will be an overkill since it'll add another click for the users who are there to read the blogs.

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have changed the code accordingly for view more button. But I did'nt understand the point where you said -> "How is this different than 1 or 2? ". I'll attach the screenshots. Will be waiting on your feedback. Thanks!!
Screenshot from 2024-02-16 05-10-52

**Comment by nehagup** [comment]
> Hey @nehagup I have changed the code accordingly for view more button. 

This looks good, just please reduce the `pt`. 

> But I didn't understand the point where you said -> "How is this different than 1 or 2? ". I'll attach the screenshots. Will be waiting on your feedback. Thanks!!

please make the PR, I think I got what you did.

**Comment by Aditya-eddy** [comment]
Hey @nehagup I've also added the show less button. I'll Attach the ScreenShots. Thanks!!
Screenshot from 2024-02-16 16-34-57
Screenshot from 2024-02-16 16-34-48

**Comment by nehagup** [comment]
@Aditya-eddy is the PR ready for review? please confirm if there are build errors.

**Comment by Aditya-eddy** [comment]
Yes @nehagup we can review it. I've checked it for build error. Thanks!!

**Review by nehagup — CHANGES_REQUESTED** [review]
Hey @Aditya-eddy this has introduced a bug, the blog category doesn't switch when I click on blog from other category. Example - I had click a `technology` category blog and it rendered the blog on /community/tech-blog-slug 

Screenshot 2024-02-17 at 7 11 43 PM

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have merged the conflicts. I think It should be working fine now. Thanks!!

**Review by nehagup — COMMENTED** [review]
@Aditya-eddy now the same thing happening for community blogs 

Screenshot 2024-02-17 at 8 06 10 PM

**Comment by Aditya-eddy** [comment]
Hey @nehagup I am sorry for above confusion. Hope I have solved the issue. Thanks!!

**Comment by Aditya-eddy** [comment]
Hey @nehagup This how currently the TOC will look.
1. On Larger screens It would look something like this 
Screenshot from 2024-02-19 09-10-22
2. On smaller screens it would be converted in to dropdown menu. Like this:-
Screenshot from 2024-02-19 09-10-22
We can the TOC left or right based on your design choice. WIll be waiting on feedback. Thanks!!

**Review by nehagup — COMMENTED** [review]
Hey! @Aditya-eddy tried again, it's still rendering tech blogs under community url.

 
Screenshot 2024-02-19 at 2 03 51 PM

**Comment by Aditya-eddy** [comment]
Hey @nehagup what I think is happening is. In our previous PR merge [issue](https://github.com/keploy/blog-website/commit/94858695bf1174d03c47b69526725657bfd1b11d) and our current  realease. The tech Blogs on the HomePage are routing to "/community/slug" and the Community Blogs are routing to "/tech/blogs". I'll attach the screenshots of the current release.
I'll also be pushing the changes to correct. If I am wrong about the issue please correct me. Thanks Will be waiting on the Feedback.
Screenshot from 2024-02-19 14-33-27

**Comment by nehagup** [comment]
> Hey @nehagup what I think is happening is. In our previous PR merge [issue](https://github.com/keploy/blog-website/commit/94858695bf1174d03c47b69526725657bfd1b11d) and our current realease. The tech Blogs on the HomePage are routing to "/community/slug" and the Community Blogs are routing to "/tech/blogs". I'll attach the screenshots of the current release. I'll also be pushing the changes to correct. If I am wrong about the issue please correct me. Thanks Will be waiting on the Feedback. Screenshot from 2024-02-19 14-33-27

@Aditya-eddy I'm still facing this issue. 2/3 tech blogs are leading to community url

**Comment by Aditya-eddy** [comment]
@nehagup But it's showing correctly on my device locally. Here-
[Screencast from 19-02-24 05:04:42 PM IST.webm](https://github.com/keploy/blog-website/assets/70089590/a72eacd7-ccb6-450f-b33a-5eb7dc1a74a9)

**Comment by nehagup** [comment]
> @nehagup But it's showing correctly on my device locally. Here- [Screencast from 19-02-24 05:04:42 PM IST.webm](https://github.com/keploy/blog-website/assets/70089590/a72eacd7-ccb6-450f-b33a-5eb7dc1a74a9)

It's an intermittent issue, I get it randomly. 

Can you please try going to tech blogs from community blogs and vice versa for 10 times in a loop and see if you're able to reproduce?

**Comment by nehagup** [comment]
Hi @Aditya-eddy were you able to replicate the issue?

**Comment by Aditya-eddy** [comment]
Will be seeing if it's working or not. WIll submiting the changed pr soon.

**Comment by Aditya-eddy** [comment]
Was not able to recreate the issue stated above hence closed it!

**Comment by nehagup** [comment]
@Aditya-eddy let me try fixing this, can you please push the changes to a branch?

**Pull request closed without merging**
