### PR TITLE
Adding the tags

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the [Issue](https://github.com/keploy/keploy/issues/1591).

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have added the tag's Page at 'blog/tags' and also a slug for indivisual tags. For ex:- 'blog/tags/tags-name'.
I'll attach the relevant screenshots and videos. We can totally discuss the designs. Will be waiting on the feedback. Thanks.!!
Screenshot from 2024-02-18 01-20-12
[Screencast from 18-02-24 01:18:34 AM IST.webm](https://github.com/keploy/blog-website/assets/70089590/2714b796-9cc0-469a-96a7-e115a84de633)
Screenshot from 2024-02-18 01-18-25

**Review by nehagup — COMMENTED** [review]
Thanks @Aditya-eddy ! 
I think we'd need little margin here! 
 
Screenshot 2024-02-19 at 4 09 57 PM


Also, the title, description of /tags as well as /tag/<tag-name> pages needs to be set, say, Keploy Blog | Golang Posts

**Comment by Aditya-eddy** [comment]
Hey @nehagup Upon click on the tags. It will lead to "tag/tag-name", On that page posts which includes this tags will be displayed. Working the description and margin. Thanks for the feedback !!

**Comment by Aditya-eddy** [comment]
Hey @nehagup this is how currently the "blog/tags" and "blog/tags/tag-name" is structured:-
1. This is how tags will be displayed on posts.
Screenshot from 2024-02-21 11-11-29
2. This is how "blog/tags" will look (ps- added the bottom margin)
Screenshot from 2024-02-21 11-11-13
3. This is how "blog/tags/tag-name" will look. It will displayed the details something like this:-
Screenshot from 2024-02-21 11-11-00

will be waiting on the feedback. Thanks!!

**Comment by nehagup** [comment]
> 1. This is how tags will be displayed on posts.

looks good!


> 2. This is how "blog/tags" will look (ps- added the bottom margin)

looks good!

> 3. This is how "blog/tags/tag-name" will look. It will displayed the details something like this:-

Need to correct the title and description, right now it's showing just "Keploy" on the page title

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have changed the title and description of page as well as layout. I'll attach the screenshots and you can view them and can be changes. WIll be waiting on the feedback. Thanks!!
1.
Screenshot from 2024-02-22 08-48-44
2.
Screenshot from 2024-02-22 08-48-19

**Comment by Aditya-eddy** [comment]
Hey @nehagup I also that favicons where breaking. I have fixed them now. I'll also attach the screenshots. Also fixes this [issue](https://github.com/keploy/keploy/issues/1504). I'll attach the screenshots here.
1.
Screenshot from 2024-02-22 10-25-46

**Comment by Aditya-eddy** [comment]
Hey @nehagup any updates on this?

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
Thanks for the PR @Aditya-eddy ! :)

**Pull request merged**
