### PR TITLE
Standardize Single Blog Post Page Design

### PR DESCRIPTION
**Pull request by its-kunal**
This branch fixes the issue - #1238
@contributors, please suggest layout changes for this pull request.

### CODE REVIEW

**Comment by its-kunal** [comment]
Hey @nehagup, please review my pull request. It standardize as given reference of GitHub copilot page from the issue - #1238

**Comment by its-kunal** [comment]
Here's are the changes i have done compared to main branch


https://github.com/keploy/blog-website/assets/92196937/60d0f02a-8b26-4e97-9cb5-f514c636da31

**Review by nehagup — COMMENTED** [review]
thanks for the initiative @its-kunal ! It'll be great if you can please create a discussion with proposed wireframes/design first and once finalised it'll be easier to move forward. How does that sound?

**Comment by its-kunal** [comment]
Thanks @nehagup, wireframes and design sound great to me. Can I use Figma for creating wireframes or any other tool? Please suggest

**Comment by nehagup** [comment]
@its-kunal are you still working on this?

**Comment by its-kunal** [comment]
@nehagup Yes I'm still working on the design part.

**Comment by nehagup** [comment]
Hey @its-kunal I'm closing this for now. Once you have the design ready, please feel free to re-open this. :)

**Comment by its-kunal** [comment]
Sure , @nehagup

**Pull request closed without merging**
