### PR TITLE
Adding the Table of Contents

### PR DESCRIPTION
**Pull request by Aditya-eddy**
Fixes the [Issue](https://github.com/keploy/keploy/issues/1240).

### CODE REVIEW

**Comment by Aditya-eddy** [comment]
Hey @nehagup I have applied the Toc. It will Show the contents which have h1,h2,h3,h4 tags in it. It will mostly start with Intro and end at more stories. I'll attach the videos for more context. You're feedback will be most appreciated on the design as well as the functionality. Thanks!!
[Screencast from 16-02-24 02:51:55 PM IST.webm](https://github.com/keploy/blog-website/assets/70089590/45788cd0-cbe3-46b8-805d-6a1958943d99)

**Comment by nehagup** [comment]
@Aditya-eddy how about we keep the design more subtle? something like what we have on docs website as well?

Screenshot 2024-02-16 at 7 23 22 PM

**Comment by nehagup** [comment]
> Hey @nehagup This how currently the TOC will look.


Hey! have you pushed the changes already? I tried running it locally, couldn't get ToC for any post

> 1. On Larger screens It would look something like this

From the image I see everything is bold right now, how about we make the font weight lighter and font size .875rem, line height 1.25rem?

> 2. On smaller screens it would be converted in to dropdown menu. Like this:-

From the image it looks fine. 


>  I have 1 doubt regarding the design. As we can see the TOC is currently congested. I feel we should change the layout for the post as it's crowding the space.

Happy to take any suggestions you may have. :)

**Comment by Aditya-eddy** [comment]
Hey @nehagup how about this. I have styled this if you approve this I'll Push the changes.
**Addressing the previous issue**
1. Yes I did push all the changes. I don't know why It did'nt work.
2. Font Size and line height have been set accordingly.
Screenshot from 2024-02-19 15-30-15

**Comment by nehagup** [comment]
> Hey @nehagup how about this. I have styled this if you approve this I'll Push the changes. **Addressing the previous issue**
> 
> 1. Yes I did push all the changes. I don't know why It did'nt work.
> 2. Font Size and line height have been set accordingly.
>    Screenshot from 2024-02-19 15-30-15

Looks good! Ship it! 👏

**Review by nehagup — COMMENTED** [review]
Looks good! Just need to resolve the build err. 

```

 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Collecting page data
   Generating static pages (0/238)  [    ]TypeError: Cannot read properties of undefined (reading 'content')
    at Post (/Users/neha/open-source/blog-website/.next/server/pages/community/[slug].js:1:1526)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)

Error occurred prerendering page "/community/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'content')
    at Post (/Users/neha/open-source/blog-website/.next/server/pages/community/[slug].js:1:1526)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
TypeError: Cannot read properties of undefined (reading 'content')
    at Post (/Users/neha/open-source/blog-website/.next/server/pages/technology/[slug].js:1:1526)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)

Error occurred prerendering page "/technology/[slug]". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'content')
    at Post (/Users/neha/open-source/blog-website/.next/server/pages/technology/[slug].js:1:1526)
    at Wc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/Users/neha/open-source/blog-website/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:479)
 ✓ Generating static pages (238/238)

> Export encountered errors on following paths:
	/community/[slug]
	/technology/[slug]
```

**Comment by Aditya-eddy** [comment]
Hey @nehagup sorry build errors. I have resolved them thanks!!

**Review by nehagup — APPROVED** [review]

**Comment by nehagup** [comment]
No worries @Aditya-eddy ! Thanks for the PR!

**Pull request merged**
