### PR TITLE
Blog Website Header to Match Main Website

### PR DESCRIPTION
**Pull request by sahadat-sk**
### Description
Fixes issue: [#1235](https://github.com/keploy/keploy/issues/1235)

### Screenshots
image
image

### CODE REVIEW

**Review by Arindam200 — APPROVED** [review]

**Comment by nehagup** [comment]
@sahadat-sk thanks for the PR, @aniketbamotra shall review it soon.

**Comment by aniketbamotra** [comment]
The header is not responsive when a blog is open. 

image

and the hamburger menu doesn't have the SVG animation of transforming into a "cross". Plus there is no fade-in effect like the homepage's menu.

**Comment by sahadat-sk** [comment]
@aniketbamotra I've fixed the issues that you mentioned, can you review them now?

**Comment by aniketbamotra** [comment]
Cool! It's working fine! But add the fade in effect when the mobile menu opens.

**Pull request merged**
