### PR TITLE
Fix: Keploy Logo, Title Inconsistencies, View All Posts

### PR DESCRIPTION
**Pull request by its-kunal**
This branch fixes the issue - #1594 of keploy/keploy. [Issue Link](https://github.com/keploy/keploy/issues/1594)

This issue fixes - 
- [x] Keploy logo in our blog articles lacks an alt attribute.
- [x] inconsistencies in the title casing of our blog articles, some titles are not following the standard title case format - it should all be titlecase
- [x] View All Posts text needs to be cleaner and more subtle
- [ ] Need to show author bio - profile description, images to improve credibility of the blog with author
For last issue. please mention which API do we need to use for author avatar, bio.

@nehagup please review my pull request.

### CODE REVIEW

**Comment by nehagup** [comment]
@its-kunal i've recorded the video - https://jam.dev/c/7d996776-4e09-4fe9-8b3b-3ddce3fbba82

**Comment by its-kunal** [comment]
@nehagup thanks for pointing this out. I will fix this soon

**Comment by its-kunal** [comment]
@nehagup, This error also persists with a table of content items.

**Comment by its-kunal** [comment]
Hey @nehagup, successfully solved the issue, this issue also solves the issue of table of contents not working.

**Comment by its-kunal** [comment]
@nehagup, Please review my PR. It solves the issue of "More Stories" and also "Table of Contents" in more stories.

**Review by nehagup — COMMENTED** [review]
Hi @its-kunal ! I'm still facing this issue on the "Viww All Post" button. 

https://jam.dev/c/8792a225-faea-4d0d-b1c0-2f4674dfc3b9

**Comment by its-kunal** [comment]
@nehagup Yes, I have figured out the error and pushed the required changes.

**Review by nehagup — APPROVED** [review]
LGTM! Thanks! 👏

**Pull request merged**
