### PR TITLE
Fix: change breakpoint for large screens.

### PR DESCRIPTION
**Pull request by its-kunal**
This PR fixes the [issue](https://github.com/keploy/keploy/issues/1771)

- Change large screen breakpoint values corresponding to tailwindcss.

### CODE REVIEW

**Review by Hermione2408 — COMMENTED** [review]
This doesn't fix the issue but yes we should fix the breakpoint, we can merge this @nehagup

**Comment by its-kunal** [comment]
Hey @Hermione2408, Here's the sticky effect for small-mid sized screens - [Link](https://jam.dev/c/d5e2969a-3de5-4789-977d-b86724868181). If this fixes the issue i will make changes for the layout.

**Comment by Hermione2408** [comment]
> Hey @Hermione2408, Here's the sticky effect for small-mid sized screens - [Link](https://jam.dev/c/d5e2969a-3de5-4789-977d-b86724868181). If this fixes the issue i will make changes for the layout.

Hey @its-kunal this is not the correct fix for this as it will stay persistent throughout and this is not what we exactly want

**Comment by its-kunal** [comment]
@Hermione2408, Ok do we need to change the layout for post body? 
can you please tell the requirements for the Table of Contents Components.

**Comment by Hermione2408** [comment]
> @Hermione2408, Ok do we need to change the layout for post body? can you please tell the requirements for the Table of Contents Components.

Hey @its-kunal If you checkout to this size you can see that now table of content's content is coming in middle with dropdown we need to fix for it, can be done by moving dropdown on top for this width 
To replicate you can checkout to nesthub screen size
Screenshot from 2024-04-08 12-45-27

**Comment by its-kunal** [comment]
Hey @Hermione2408, thanks for pointing this out, I made the changes to fix this.

**Review by nehagup — COMMENTED** [review]
@its-kunal thanks for the PR! Looks good to me!  Please resolve the conflicts and we should be ready to merge.

**Review by Hermione2408 — APPROVED** [review]
LGTM @nehagup

**Review by nehagup — APPROVED** [review]

**Pull request merged**
